#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MileageGauge.Resource", IsApplication=true)]

namespace MileageGauge
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MileageGauge.DI.Resource.String.ApplicationName = global::MileageGauge.Resource.String.ApplicationName;
			global::MileageGauge.DI.Resource.String.Hello = global::MileageGauge.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int item_touch_helper_swipe_escape_max_velocity = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int item_touch_helper_swipe_escape_velocity = 2130968578;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050009
			public const int AverageMPGText = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int CityText = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int CombinedText = 2131034118;
			
			// aapt resource value: 0x7f050012
			public const int ConnectingLayout = 2131034130;
			
			// aapt resource value: 0x7f050001
			public const int DeviceName = 2131034113;
			
			// aapt resource value: 0x7f050013
			public const int DeviceRecyclerView = 2131034131;
			
			// aapt resource value: 0x7f050019
			public const int EngineText = 2131034137;
			
			// aapt resource value: 0x7f050004
			public const int EpaMileageLayout = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int HighwayText = 2131034119;
			
			// aapt resource value: 0x7f050010
			public const int InstantMPGText = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int MPHText = 2131034127;
			
			// aapt resource value: 0x7f050002
			public const int MainLayout = 2131034114;
			
			// aapt resource value: 0x7f050017
			public const int MakeText = 2131034135;
			
			// aapt resource value: 0x7f050011
			public const int MileageBack = 2131034129;
			
			// aapt resource value: 0x7f050018
			public const int ModelText = 2131034136;
			
			// aapt resource value: 0x7f05001a
			public const int RefreshVehicleButton = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int StartScanningButton = 2131034139;
			
			// aapt resource value: 0x7f05000e
			public const int ThrottleText = 2131034126;
			
			// aapt resource value: 0x7f050014
			public const int VehicleInfoLayout = 2131034132;
			
			// aapt resource value: 0x7f050003
			public const int VehicleText = 2131034115;
			
			// aapt resource value: 0x7f050016
			public const int YearText = 2131034134;
			
			// aapt resource value: 0x7f05000a
			public const int gridLayout1 = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int linearLayout1 = 2131034120;
			
			// aapt resource value: 0x7f05000b
			public const int textView1 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int textView2 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int textView3 = 2131034125;
			
			// aapt resource value: 0x7f050015
			public const int textView6 = 2131034133;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BluetoothDeviceLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Diagnostic = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LiveMileage = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int VehicleSelection = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int default_menu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
