#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MileageGauge.Resource", IsApplication=true)]

namespace MileageGauge
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MileageGauge.DI.Resource.String.ApplicationName = global::MileageGauge.Resource.String.ApplicationName;
			global::MileageGauge.DI.Resource.String.Hello = global::MileageGauge.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060007
			public const int AverageMPGText = 2131099655;
			
			// aapt resource value: 0x7f060003
			public const int CityText = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int CombinedText = 2131099652;
			
			// aapt resource value: 0x7f060010
			public const int ConnectingLayout = 2131099664;
			
			// aapt resource value: 0x7f060016
			public const int EngineText = 2131099670;
			
			// aapt resource value: 0x7f060002
			public const int EpaMileageLayout = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int HighwayText = 2131099653;
			
			// aapt resource value: 0x7f06000e
			public const int InstantMPGText = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int MPHText = 2131099661;
			
			// aapt resource value: 0x7f060000
			public const int MainLayout = 2131099648;
			
			// aapt resource value: 0x7f060014
			public const int MakeText = 2131099668;
			
			// aapt resource value: 0x7f06000f
			public const int MileageBack = 2131099663;
			
			// aapt resource value: 0x7f060015
			public const int ModelText = 2131099669;
			
			// aapt resource value: 0x7f060017
			public const int RefreshVehicleButton = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int StartScanningButton = 2131099672;
			
			// aapt resource value: 0x7f06000c
			public const int ThrottleText = 2131099660;
			
			// aapt resource value: 0x7f060011
			public const int VehicleInfoLayout = 2131099665;
			
			// aapt resource value: 0x7f060001
			public const int VehicleText = 2131099649;
			
			// aapt resource value: 0x7f060013
			public const int YearText = 2131099667;
			
			// aapt resource value: 0x7f060008
			public const int gridLayout1 = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int linearLayout1 = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int textView1 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int textView2 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int textView3 = 2131099659;
			
			// aapt resource value: 0x7f060012
			public const int textView6 = 2131099666;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Diagnostic = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LiveMileage = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int VehicleSelection = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int default_menu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
